// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	apiv1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1"
	scheme "github.com/envoyproxy/ai-gateway/api/v1beta1/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GatewayConfigsGetter has a method to return a GatewayConfigInterface.
// A group's client should implement this interface.
type GatewayConfigsGetter interface {
	GatewayConfigs(namespace string) GatewayConfigInterface
}

// GatewayConfigInterface has methods to work with GatewayConfig resources.
type GatewayConfigInterface interface {
	Create(ctx context.Context, gatewayConfig *apiv1beta1.GatewayConfig, opts v1.CreateOptions) (*apiv1beta1.GatewayConfig, error)
	Update(ctx context.Context, gatewayConfig *apiv1beta1.GatewayConfig, opts v1.UpdateOptions) (*apiv1beta1.GatewayConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gatewayConfig *apiv1beta1.GatewayConfig, opts v1.UpdateOptions) (*apiv1beta1.GatewayConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1beta1.GatewayConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1beta1.GatewayConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1beta1.GatewayConfig, err error)
	GatewayConfigExpansion
}

// gatewayConfigs implements GatewayConfigInterface
type gatewayConfigs struct {
	*gentype.ClientWithList[*apiv1beta1.GatewayConfig, *apiv1beta1.GatewayConfigList]
}

// newGatewayConfigs returns a GatewayConfigs
func newGatewayConfigs(c *AigatewayV1beta1Client, namespace string) *gatewayConfigs {
	return &gatewayConfigs{
		gentype.NewClientWithList[*apiv1beta1.GatewayConfig, *apiv1beta1.GatewayConfigList](
			"gatewayconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1beta1.GatewayConfig { return &apiv1beta1.GatewayConfig{} },
			func() *apiv1beta1.GatewayConfigList { return &apiv1beta1.GatewayConfigList{} },
		),
	}
}
