# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

# This example demonstrates a comprehensive GatewayConfig with OpenTelemetry tracing configuration
# that can be shared across multiple Gateways.

apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: GatewayConfig
metadata:
  name: comprehensive-config
  namespace: default
spec:
  extProc:
    kubernetes:
      env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.monitoring:4317"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "api-key=your-secret-key"
        - name: OTEL_SERVICE_NAME
          value: "ai-gateway-production"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_traceidratio"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        - name: LOG_LEVEL
          value: "info"
        - name: ENABLE_DEBUG_METRICS
          value: "false"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: production-ai-gateway
  namespace: default
  annotations:
    aigateway.envoyproxy.io/gateway-config: comprehensive-config
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: staging-ai-gateway
  namespace: default
  annotations:
    aigateway.envoyproxy.io/gateway-config: comprehensive-config
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 8081
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: example-backend
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: api.openai.com
        port: 443
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: example-backend
  namespace: default
spec:
  schema:
    name: OpenAI
    version: v1
  backendRef:
    name: example-backend
    kind: Backend
    group: gateway.envoyproxy.io
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: example-route
  namespace: default
spec:
  parentRefs:
    - name: production-ai-gateway
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - backendRefs:
        - name: example-backend
