// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GatewayConfigLister helps list GatewayConfigs.
// All objects returned here must be treated as read-only.
type GatewayConfigLister interface {
	// List lists all GatewayConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.GatewayConfig, err error)
	// GatewayConfigs returns an object that can list and get GatewayConfigs.
	GatewayConfigs(namespace string) GatewayConfigNamespaceLister
	GatewayConfigListerExpansion
}

// gatewayConfigLister implements the GatewayConfigLister interface.
type gatewayConfigLister struct {
	listers.ResourceIndexer[*apiv1alpha1.GatewayConfig]
}

// NewGatewayConfigLister returns a new GatewayConfigLister.
func NewGatewayConfigLister(indexer cache.Indexer) GatewayConfigLister {
	return &gatewayConfigLister{listers.New[*apiv1alpha1.GatewayConfig](indexer, apiv1alpha1.Resource("gatewayconfig"))}
}

// GatewayConfigs returns an object that can list and get GatewayConfigs.
func (s *gatewayConfigLister) GatewayConfigs(namespace string) GatewayConfigNamespaceLister {
	return gatewayConfigNamespaceLister{listers.NewNamespaced[*apiv1alpha1.GatewayConfig](s.ResourceIndexer, namespace)}
}

// GatewayConfigNamespaceLister helps list and get GatewayConfigs.
// All objects returned here must be treated as read-only.
type GatewayConfigNamespaceLister interface {
	// List lists all GatewayConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.GatewayConfig, err error)
	// Get retrieves the GatewayConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.GatewayConfig, error)
	GatewayConfigNamespaceListerExpansion
}

// gatewayConfigNamespaceLister implements the GatewayConfigNamespaceLister
// interface.
type gatewayConfigNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.GatewayConfig]
}
