// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// QuotaPolicyLister helps list QuotaPolicies.
// All objects returned here must be treated as read-only.
type QuotaPolicyLister interface {
	// List lists all QuotaPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.QuotaPolicy, err error)
	// QuotaPolicies returns an object that can list and get QuotaPolicies.
	QuotaPolicies(namespace string) QuotaPolicyNamespaceLister
	QuotaPolicyListerExpansion
}

// quotaPolicyLister implements the QuotaPolicyLister interface.
type quotaPolicyLister struct {
	listers.ResourceIndexer[*apiv1alpha1.QuotaPolicy]
}

// NewQuotaPolicyLister returns a new QuotaPolicyLister.
func NewQuotaPolicyLister(indexer cache.Indexer) QuotaPolicyLister {
	return &quotaPolicyLister{listers.New[*apiv1alpha1.QuotaPolicy](indexer, apiv1alpha1.Resource("quotapolicy"))}
}

// QuotaPolicies returns an object that can list and get QuotaPolicies.
func (s *quotaPolicyLister) QuotaPolicies(namespace string) QuotaPolicyNamespaceLister {
	return quotaPolicyNamespaceLister{listers.NewNamespaced[*apiv1alpha1.QuotaPolicy](s.ResourceIndexer, namespace)}
}

// QuotaPolicyNamespaceLister helps list and get QuotaPolicies.
// All objects returned here must be treated as read-only.
type QuotaPolicyNamespaceLister interface {
	// List lists all QuotaPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.QuotaPolicy, err error)
	// Get retrieves the QuotaPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.QuotaPolicy, error)
	QuotaPolicyNamespaceListerExpansion
}

// quotaPolicyNamespaceLister implements the QuotaPolicyNamespaceLister
// interface.
type quotaPolicyNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.QuotaPolicy]
}
