// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	scheme "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// QuotaPoliciesGetter has a method to return a QuotaPolicyInterface.
// A group's client should implement this interface.
type QuotaPoliciesGetter interface {
	QuotaPolicies(namespace string) QuotaPolicyInterface
}

// QuotaPolicyInterface has methods to work with QuotaPolicy resources.
type QuotaPolicyInterface interface {
	Create(ctx context.Context, quotaPolicy *apiv1alpha1.QuotaPolicy, opts v1.CreateOptions) (*apiv1alpha1.QuotaPolicy, error)
	Update(ctx context.Context, quotaPolicy *apiv1alpha1.QuotaPolicy, opts v1.UpdateOptions) (*apiv1alpha1.QuotaPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, quotaPolicy *apiv1alpha1.QuotaPolicy, opts v1.UpdateOptions) (*apiv1alpha1.QuotaPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.QuotaPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.QuotaPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.QuotaPolicy, err error)
	QuotaPolicyExpansion
}

// quotaPolicies implements QuotaPolicyInterface
type quotaPolicies struct {
	*gentype.ClientWithList[*apiv1alpha1.QuotaPolicy, *apiv1alpha1.QuotaPolicyList]
}

// newQuotaPolicies returns a QuotaPolicies
func newQuotaPolicies(c *AigatewayV1alpha1Client, namespace string) *quotaPolicies {
	return &quotaPolicies{
		gentype.NewClientWithList[*apiv1alpha1.QuotaPolicy, *apiv1alpha1.QuotaPolicyList](
			"quotapolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.QuotaPolicy { return &apiv1alpha1.QuotaPolicy{} },
			func() *apiv1alpha1.QuotaPolicyList { return &apiv1alpha1.QuotaPolicyList{} },
		),
	}
}
