// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGatewayConfigs implements GatewayConfigInterface
type fakeGatewayConfigs struct {
	*gentype.FakeClientWithList[*v1alpha1.GatewayConfig, *v1alpha1.GatewayConfigList]
	Fake *FakeAigatewayV1alpha1
}

func newFakeGatewayConfigs(fake *FakeAigatewayV1alpha1, namespace string) apiv1alpha1.GatewayConfigInterface {
	return &fakeGatewayConfigs{
		gentype.NewFakeClientWithList[*v1alpha1.GatewayConfig, *v1alpha1.GatewayConfigList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("gatewayconfigs"),
			v1alpha1.SchemeGroupVersion.WithKind("GatewayConfig"),
			func() *v1alpha1.GatewayConfig { return &v1alpha1.GatewayConfig{} },
			func() *v1alpha1.GatewayConfigList { return &v1alpha1.GatewayConfigList{} },
			func(dst, src *v1alpha1.GatewayConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.GatewayConfigList) []*v1alpha1.GatewayConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.GatewayConfigList, items []*v1alpha1.GatewayConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
