// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeQuotaPolicies implements QuotaPolicyInterface
type fakeQuotaPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.QuotaPolicy, *v1alpha1.QuotaPolicyList]
	Fake *FakeAigatewayV1alpha1
}

func newFakeQuotaPolicies(fake *FakeAigatewayV1alpha1, namespace string) apiv1alpha1.QuotaPolicyInterface {
	return &fakeQuotaPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.QuotaPolicy, *v1alpha1.QuotaPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("quotapolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("QuotaPolicy"),
			func() *v1alpha1.QuotaPolicy { return &v1alpha1.QuotaPolicy{} },
			func() *v1alpha1.QuotaPolicyList { return &v1alpha1.QuotaPolicyList{} },
			func(dst, src *v1alpha1.QuotaPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.QuotaPolicyList) []*v1alpha1.QuotaPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.QuotaPolicyList, items []*v1alpha1.QuotaPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
