// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1"
	apiv1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1/client/clientset/versioned/typed/api/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBackendSecurityPolicies implements BackendSecurityPolicyInterface
type fakeBackendSecurityPolicies struct {
	*gentype.FakeClientWithList[*v1beta1.BackendSecurityPolicy, *v1beta1.BackendSecurityPolicyList]
	Fake *FakeAigatewayV1beta1
}

func newFakeBackendSecurityPolicies(fake *FakeAigatewayV1beta1, namespace string) apiv1beta1.BackendSecurityPolicyInterface {
	return &fakeBackendSecurityPolicies{
		gentype.NewFakeClientWithList[*v1beta1.BackendSecurityPolicy, *v1beta1.BackendSecurityPolicyList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("backendsecuritypolicies"),
			v1beta1.SchemeGroupVersion.WithKind("BackendSecurityPolicy"),
			func() *v1beta1.BackendSecurityPolicy { return &v1beta1.BackendSecurityPolicy{} },
			func() *v1beta1.BackendSecurityPolicyList { return &v1beta1.BackendSecurityPolicyList{} },
			func(dst, src *v1beta1.BackendSecurityPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.BackendSecurityPolicyList) []*v1beta1.BackendSecurityPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.BackendSecurityPolicyList, items []*v1beta1.BackendSecurityPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
