// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1"
	apiv1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1/client/clientset/versioned/typed/api/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGatewayConfigs implements GatewayConfigInterface
type fakeGatewayConfigs struct {
	*gentype.FakeClientWithList[*v1beta1.GatewayConfig, *v1beta1.GatewayConfigList]
	Fake *FakeAigatewayV1beta1
}

func newFakeGatewayConfigs(fake *FakeAigatewayV1beta1, namespace string) apiv1beta1.GatewayConfigInterface {
	return &fakeGatewayConfigs{
		gentype.NewFakeClientWithList[*v1beta1.GatewayConfig, *v1beta1.GatewayConfigList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("gatewayconfigs"),
			v1beta1.SchemeGroupVersion.WithKind("GatewayConfig"),
			func() *v1beta1.GatewayConfig { return &v1beta1.GatewayConfig{} },
			func() *v1beta1.GatewayConfigList { return &v1beta1.GatewayConfigList{} },
			func(dst, src *v1beta1.GatewayConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.GatewayConfigList) []*v1beta1.GatewayConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.GatewayConfigList, items []*v1beta1.GatewayConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
