// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1"
	apiv1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1/client/clientset/versioned/typed/api/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAIGatewayRoutes implements AIGatewayRouteInterface
type fakeAIGatewayRoutes struct {
	*gentype.FakeClientWithList[*v1beta1.AIGatewayRoute, *v1beta1.AIGatewayRouteList]
	Fake *FakeAigatewayV1beta1
}

func newFakeAIGatewayRoutes(fake *FakeAigatewayV1beta1, namespace string) apiv1beta1.AIGatewayRouteInterface {
	return &fakeAIGatewayRoutes{
		gentype.NewFakeClientWithList[*v1beta1.AIGatewayRoute, *v1beta1.AIGatewayRouteList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("aigatewayroutes"),
			v1beta1.SchemeGroupVersion.WithKind("AIGatewayRoute"),
			func() *v1beta1.AIGatewayRoute { return &v1beta1.AIGatewayRoute{} },
			func() *v1beta1.AIGatewayRouteList { return &v1beta1.AIGatewayRouteList{} },
			func(dst, src *v1beta1.AIGatewayRouteList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.AIGatewayRouteList) []*v1beta1.AIGatewayRoute {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.AIGatewayRouteList, items []*v1beta1.AIGatewayRoute) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
