// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1"
	apiv1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1/client/clientset/versioned/typed/api/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAIServiceBackends implements AIServiceBackendInterface
type fakeAIServiceBackends struct {
	*gentype.FakeClientWithList[*v1beta1.AIServiceBackend, *v1beta1.AIServiceBackendList]
	Fake *FakeAigatewayV1beta1
}

func newFakeAIServiceBackends(fake *FakeAigatewayV1beta1, namespace string) apiv1beta1.AIServiceBackendInterface {
	return &fakeAIServiceBackends{
		gentype.NewFakeClientWithList[*v1beta1.AIServiceBackend, *v1beta1.AIServiceBackendList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("aiservicebackends"),
			v1beta1.SchemeGroupVersion.WithKind("AIServiceBackend"),
			func() *v1beta1.AIServiceBackend { return &v1beta1.AIServiceBackend{} },
			func() *v1beta1.AIServiceBackendList { return &v1beta1.AIServiceBackendList{} },
			func(dst, src *v1beta1.AIServiceBackendList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.AIServiceBackendList) []*v1beta1.AIServiceBackend {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.AIServiceBackendList, items []*v1beta1.AIServiceBackend) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
