# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

code_review:
  disable: false
  pull_request_opened:
    help: false
    summary: false
    code_review: false
    include_drafts: false
